schema_version: 1

context:
  name: types-six
  version: 1.17.0.20251009

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: efe03064ecd0ffb0f7afe133990a2398d8493d8d1c1cc10ff3dfe476d57ba44f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=${{ python_min }}
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - requirements:
      run:
        - pip
        - python >=${{ python_min }}
    script:
      - pip check

  - package_contents:
      site_packages:
        - six-stubs/__init__.pyi

about:
  summary: Typing stubs for six
  license: Apache-2.0 AND MIT
  license_file: LICENSE
  homepage: https://github.com/python/typeshed

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
